// Centralized API endpoint path constants
export const ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  SEND_OTP: '/auth/otp/send',
  VERIFY_OTP: '/auth/otp/verify',
  ME: '/auth/me',
  LOGOUT: '/auth/logout',
  PROJECTS: '/projects',
  FAVORITES: '/favorites',
  LISTINGS: '/listings',
  LISTING_SUGGESTIONS: '/listings/suggestions',
  GROUPS: '/groups',
  GROUP_SUGGESTIONS: '/groups/suggestions',
  PROFILE: '/profile',
  BRANDING: '/branding',
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_SETTINGS: '/notification-settings',
  MEDIA: '/media',
  TEMPLATES: '/templates',
  UPLOAD: '/upload',
  CATEGORIES: '/categories',
};
